self_filter:
  topic_in: head_mount_kinect/depth_registered/points
  topic_out: cloud_out
  use_rgb: true
  keep_organized: true

  self_see_links: [
    name: r_elbow_flex_link,
    name: r_forearm_link,
    name: r_forearm_roll_link,
    name: r_gripper_l_finger_link,
    name: r_gripper_l_finger_tip_link,
    #name: r_gripper_motor_accelerometer_link,
    #name: r_gripper_motor_screw_link,
    #name: r_gripper_motor_slider_link,
    name: r_gripper_palm_link,
    name: r_gripper_r_finger_link,
    name: r_gripper_r_finger_tip_link,
    name: r_shoulder_lift_link,
    name: r_shoulder_pan_link,
    #name: r_torso_lift_side_plate_link,
    name: r_upper_arm_link,
    name: r_upper_arm_roll_link,
    name: r_wrist_flex_link,
    name: r_wrist_roll_link]